version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    build:
      context: ./
    image: notes-app-back-ts
    ports:
      - '3000:3000'

volumes:
  db:
    driver: local
