version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    build:
      context: ./
    image: notes-app-back-ts
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

volumes:
  db:
    driver: local
